remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: [Rezonator Documentation Test]
description: [This website is a test documentation site for the software Rezonator]

theme: jekyll-theme-leap-day

github:
  repository_url: https://hsuorg.github.io/hsurepo/
